import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

import 'package:common/src/services/blitz_api/sse_event.dart';
import 'package:common/src/services/log_service.dart';

/// Thin client for the subset of blitz-api we use from the TUI
/// dashboard: login (JWT), SSE subscribe. Connection lives for the
/// lifetime of the dashboard; auto-reconnect with exponential backoff
/// when the stream drops.
///
/// Not a general-purpose client — we deliberately don't pull the
/// autogenerated Dart client here (Dart 2.12 / http 0.13, no SSE).
/// Grow this file as needs arise, or replace wholesale if we adopt
/// the autogen later.
class BlitzApiClient {
  /// Base URL of the API. Default targets the local service directly
  /// (skip the nginx proxy to avoid SSE buffering gotchas).
  final Uri baseUrl;

  /// Path to the password file. Read via `sudo -n cat` so we don't
  /// need the caller to be in blitzapi's group.
  final String passwordFilePath;

  /// Backoff sequence in seconds; last value repeats indefinitely.
  static const _backoffSeconds = [1, 2, 5, 10, 30];

  BlitzApiClient({
    Uri? baseUrl,
    this.passwordFilePath = '/var/lib/blitz_api/.login-password',
  }) : baseUrl = baseUrl ?? Uri.parse('http://127.0.0.1:2121');

  String? _jwt;
  final http.Client _httpClient = http.Client();
  StreamSubscription<SseEvent>? _sseSub;
  bool _disposed = false;

  /// Event stream. Resilient to reconnects — subscribers keep seeing
  /// events after the underlying HTTP stream drops and reconnects.
  final StreamController<SseEvent> _events =
      StreamController<SseEvent>.broadcast();
  Stream<SseEvent> get events => _events.stream;

  /// Connect the SSE stream, logging in first if needed. Idempotent —
  /// calling twice is a no-op after the first start.
  Future<void> start() async {
    if (_disposed) throw StateError('BlitzApiClient is disposed');
    if (_sseSub != null) return;
    unawaited(_runWithBackoff());
  }

  Future<void> dispose() async {
    _disposed = true;
    await _sseSub?.cancel();
    _sseSub = null;
    _httpClient.close();
    if (!_events.isClosed) await _events.close();
  }

  // ── private ──────────────────────────────────────────────────

  Future<String> _readPassword() async {
    // sudo -n: non-interactive; fails fast if we can't sudo.
    final res = await Process.run('sudo', ['-n', 'cat', passwordFilePath]);
    if (res.exitCode != 0) {
      throw StateError(
        'Could not read $passwordFilePath (sudo exit ${res.exitCode}): '
        '${(res.stderr as String).trim()}',
      );
    }
    return (res.stdout as String).trim();
  }

  Future<void> _login() async {
    final password = await _readPassword();
    final url = baseUrl.resolve('/system/login');
    final resp = await _httpClient.post(
      url,
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({'password': password}),
    );
    if (resp.statusCode != 200) {
      throw StateError(
        'POST ${url.path} returned ${resp.statusCode}: ${resp.body}',
      );
    }
    // The endpoint returns the JWT as a bare JSON string: "eyJhbGc..."
    final parsed = jsonDecode(resp.body);
    if (parsed is String) {
      _jwt = parsed;
    } else if (parsed is Map && parsed['access_token'] is String) {
      _jwt = parsed['access_token'] as String;
    } else {
      throw StateError(
        'Unexpected login response body (${parsed.runtimeType}): ${resp.body}',
      );
    }
    LogService.info('BlitzApiClient: logged in (JWT cached)');
  }

  Future<void> _runWithBackoff() async {
    var attempt = 0;
    while (!_disposed) {
      try {
        if (_jwt == null) await _login();
        await _streamSse();
        // _streamSse returns normally when the server closes — treat
        // as reconnect-worthy.
      } catch (e, st) {
        LogService.warn('BlitzApi SSE error: $e');
        LogService.error('BlitzApi SSE trace', e, st);
        // 401 likely means the JWT expired; drop it and re-login.
        if (e.toString().contains('401')) _jwt = null;
      }
      if (_disposed) return;
      final wait = _backoffSeconds[
          attempt.clamp(0, _backoffSeconds.length - 1)];
      attempt++;
      await Future.delayed(Duration(seconds: wait));
    }
  }

  Future<void> _streamSse() async {
    final url = baseUrl.resolve('/sse/subscribe');
    final req = http.Request('GET', url);
    req.headers['Authorization'] = 'Bearer $_jwt';
    req.headers['Accept'] = 'text/event-stream';
    req.headers['Cache-Control'] = 'no-cache';

    final resp = await _httpClient.send(req);
    if (resp.statusCode != 200) {
      throw StateError(
        'SSE subscribe returned ${resp.statusCode}',
      );
    }

    LogService.info('BlitzApiClient: SSE connected');

    // Decode UTF-8 chunks → parse SSE frames → republish on our
    // broadcast controller.
    final chunks = resp.stream.transform(utf8.decoder);
    final completer = Completer<void>();
    _sseSub = parseSseStream(chunks).listen(
      (ev) {
        if (!_events.isClosed) _events.add(ev);
      },
      onDone: () {
        if (!completer.isCompleted) completer.complete();
      },
      onError: (e, st) {
        if (!completer.isCompleted) completer.completeError(e, st);
      },
      cancelOnError: true,
    );
    try {
      await completer.future;
    } finally {
      await _sseSub?.cancel();
      _sseSub = null;
    }
  }
}
