{
  description = "NixBlitz node configuration";

  # NB: the attic binary cache (https://attic.f44.fyi/nixblitz) is configured
  # via `nix.settings.extra-substituters` in modules/system/base.nix, NOT here.
  # A flake `nixConfig` is silently ignored unless `accept-flake-config = true`
  # (off by default — even for trusted users on some nix builds), so a block
  # here did nothing except emit "ignoring untrusted flake configuration
  # setting" warnings on every rebuild. System-level `nix.settings` is the
  # reliable mechanism. See issue #24 for why the cache exists (Pi 5 jemalloc).

  inputs = {
    # Pi 5 isn't supported by upstream NixOS — vendor kernel + firmware
    # come from this third-party flake. Pinned to a tag so refreshes
    # are explicit; bump deliberately rather than tracking `main`.
    #
    # nvmd's CI publishes the vendor kernel + page-size-16k jemalloc
    # to `nixos-raspberrypi.cachix.org` against THEIR pinned nixpkgs.
    # Both halves of that alignment matter:
    #
    # 1. `nixos-raspberrypi` deliberately does NOT follow nixpkgs.
    #    Following ours would diverge the derivation hash and force
    #    a Pi-local kernel rebuild — multi-hour aarch64 pain on
    #    every nixpkgs bump.
    # 2. Reciprocal direction below: `nixpkgs.follows =
    #    "nixos-raspberrypi/nixpkgs"`. When we ran with an
    #    independent nixpkgs, every `nix flake update` advanced ours
    #    past whatever rev nvmd's cachix last published against,
    #    and Pi rebuilds would hit cache misses + SIGBUS aborts on
    #    16K pages (cache.nixos.org's standard aarch64 builds are
    #    4K-aligned). Aligning forward fixes the whole class.
    #
    # Tradeoff accepted: x86 builds also inherit nvmd's nixpkgs rev,
    # which lags upstream by however long nvmd's tag cadence is
    # (~weekly per their release pattern — fine). x86 is the eval /
    # dev target where the lag doesn't hurt; Pi 5 is the production
    # target where cache alignment is load-bearing.
    nixos-raspberrypi = {
      url = "github:nvmd/nixos-raspberrypi/v1.20260707.1";
    };
    nixpkgs.follows = "nixos-raspberrypi/nixpkgs";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # nix-bitcoin used to be an input here, but it's pulled by the
    # bitcoind / lnd / cln plugins now via builtins.getFlake at a
    # coordinated rev. The operator's flake input list is shorter for it.
    nixblitz = {
      url = "git+https://forge.f44.fyi/f44/nixblitz_ng";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    self,
    nixpkgs,
    disko,
    nixblitz,
    nixos-raspberrypi,
  }: let
    inherit (nixpkgs) lib;

    excludedFiles = ["package.nix" "flake.nix"];

    findModules = dir: let
      entries = builtins.readDir dir;
      processEntry = name: type: let
        path = dir + "/${name}";
      in
        if type == "directory"
        then findModules path
        else if type == "regular" && lib.hasSuffix ".nix" name && !builtins.elem name excludedFiles
        then [path]
        else [];
    in
      lib.concatLists (lib.mapAttrsToList processEntry entries);

    # Read enough of the operator's config to know which platform
    # we're targeting AND to inject per-plugin config below. Used to
    # alias `nixosConfigurations.${hostname}` to the platform-correct
    # build (without it, a plain `nixos-rebuild switch --flake .`
    # defaults to `.#${hostname}` and the Pi 5 case grabs the x86
    # attribute, failing with `boot.loader.grub.devices` unset).
    blitzCfg =
      if builtins.pathExists ./config.json
      then builtins.fromJSON (builtins.readFile ./config.json)
      else {};
    blitzPlatform = blitzCfg.system.platform or "x86";
    blitzHostname = blitzCfg.system.hostname or "nixblitz";

    # User-installed plugins (see docs/decisions/plugins.md D14).
    # Activation is driven by ./plugins.list, regenerated by the TUI
    # on every install / remove / enable / disable. File format: one
    # plugin id per non-empty line. Each id resolves to a directory
    # under ./plugins/<id>/ that contains:
    #   - plugin.json: the manifest (declares `module` filename)
    #   - <module>:    the NixOS module file (default plugin.nix)
    #
    # Plugin ABI: the module is a TWO-STAGE function
    #   { pluginCfg ? {} }: { config, lib, pkgs, ... }: { … }
    # The outer stage receives the plugin's config from the main
    # config.json's `app_configs.<id>` block (single source of
    # truth — no per-plugin config.json). The inner is a standard
    # NixOS module function. We deliver pluginCfg via closure on the
    # outer stage, NOT as a named arg on the inner — because the
    # module system routes every named arg through `_module.args.<name>`,
    # which is global, so two plugins declaring `pluginCfg` as a
    # module arg would collide with `_module.args.pluginCfg' is
    # defined multiple times`. Two-stage isolates each plugin's cfg
    # inside its own closure.
    pluginModules = let
      pluginsListPath = ./plugins.list;
      pluginIds =
        if builtins.pathExists pluginsListPath
        then
          builtins.filter (s: s != "") (
            lib.splitString "\n" (builtins.readFile pluginsListPath)
          )
        else [];
      mkPluginModule = id: let
        pluginPath = ./plugins + "/${id}";
        manifest = builtins.fromJSON (
          builtins.readFile (pluginPath + "/plugin.json")
        );
        moduleFile = manifest.module or "plugin.nix";
        modulePath = pluginPath + "/${moduleFile}";
        # Plugin-specific config from the main config.json.
        # Defaults to {} — plugin manifests should provide sane
        # defaults via their config_schema, which the TUI seeds
        # into app_configs.<id> at install time.
        appConfigs = blitzCfg.app_configs or {};
        pluginCfg = appConfigs.${id} or {};
      in
        # `import modulePath` returns the outer function; calling
        # it with {pluginCfg = cfg} returns the inner module
        # function (no pluginCfg in that signature), which the
        # module system treats as a normal NixOS module.
        #
        # Plugins needing cross-app reads (e.g. blitz-api checking
        # whether lnd is enabled) get them via `config.nixblitz.
        # appConfigs.<id>.<key>` — declared as a NixOS option by
        # `templates/hosts/installed.nix`. No ABI change here; the
        # option-based path keeps the outer function signature
        # backwards-compatible with plugins that still use the
        # strict `{ pluginCfg ? {} }: …` shape.
        (import modulePath) {pluginCfg = pluginCfg;};
    in
      map mkPluginModule pluginIds;

    # Complete flake-input SOURCE set pinned into every system closure by
    # modules/system/pin-flake-sources.nix. This MUST mirror the offline
    # lock graph (nix/offline-inputs.nix's node list) EXACTLY — every
    # `type = "path"` node the lock carries has to appear here.
    #
    # Why completeness is load-bearing: first boot evaluates the path-locked
    # `~/nixblitz`, and that eval forces the FULL transitive source set, not
    # just the five top-level inputs. `nixblitz.packages.<sys>` pulls the root
    # flake's outputs → `flake-utils.lib.eachDefaultSystem` → imports
    # flake-utils → imports its `systems` input; the TUI src filtering pulls
    # nix-filter; the config-channel checks pull both unstable nixpkgs; the Pi
    # 5 safety net pulls nixos-raspberrypi's argononed / flake-compat /
    # nixos-images. The ISO bakes the full `sourcePaths` set so INSTALL works,
    # but the TARGET only ever receives what THIS attrset pins. Any lock node
    # missing here is absent on the installed node and bricks first boot
    # offline with `path '/nix/store/…-source' does not exist` — exactly the
    # `systems` (nix-systems/default, flake-utils' input) field failure.
    #
    # Merge strategy: later attrsets win. Name collisions (disko / nixpkgs /
    # nixos-raspberrypi appear in more than one source) resolve to identical
    # store paths via the offline lock's overrides, so which copy wins doesn't
    # change the pinned path set. NOTE this identity is LOAD-BEARING, not
    # incidental: if nixblitz's pinned nixos-raspberrypi rev ever diverged
    # from the top-level one, the losing copy's transitive nodes (argononed,
    # flake-compat, nixos-images, nixpkgs) would silently drop out of the pin
    # while remaining in the baked lock — and the offline-VM acceptance run
    # (plus the lock generator's all-nodes assert at ISO build) is what
    # catches that. Keep the two revs aligned deliberately.
    pinnedFlakeInputs =
      {
        inherit nixpkgs disko nixos-raspberrypi nixblitz;
      }
      // nixblitz.inputs # disko, flake-utils, nix-filter, nixos-raspberrypi, nixpkgs (follows), nixpkgs-unstable, nixpkgs-vanilla-unstable
      // nixblitz.inputs.flake-utils.inputs # systems (nix-systems/default)
      // nixos-raspberrypi.inputs; # argononed, flake-compat, nixos-images, nixpkgs
  in {
    nixosModules.default = {
      imports =
        (findModules ./modules)
        ++ pluginModules
        ++ [
          disko.nixosModules.default
          # nix-bitcoin.nixosModules.default was here; the bitcoind / lnd /
          # cln plugins now import it themselves via builtins.getFlake at a
          # coordinated rev. blitz-api and blitz-web dropped from inputs too —
          # their plugins pull the upstream modules via `builtins.getFlake`.
          # See examples_redesign/nixblitz_official_plugins/.
        ];
    };

    # Build the four canonical configurations as a separate
    # attrset, then merge in the hostname-keyed alias below. The
    # split is purely so the alias can overwrite an existing key
    # (e.g. operator's hostname is the default `nixblitz` on Pi
    # 5 — alias overrides the x86 build under that name) without
    # tripping Nix's "attribute already defined" error from two
    # static assignments to the same key.
    nixosConfigurations = let
      canonical = {
        nixblitz = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          specialArgs = {
            inherit nixblitz;
            # Complete pinned source set — see `pinnedFlakeInputs` above.
            flakeInputs = pinnedFlakeInputs;
          };
          modules = [
            ./hosts/installed.nix
            self.nixosModules.default
          ];
        };

        # Live-ISO config used by `disko-install --flake .#nixblitz-installer`.
        # Identical to nixosConfigurations.nixblitz except for passwordless
        # sudo. See docs/decisions/plugins.md (sudo posture).
        nixblitz-installer = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          specialArgs = {
            inherit nixblitz;
            # Complete pinned source set — see `pinnedFlakeInputs` above.
            flakeInputs = pinnedFlakeInputs;
          };
          modules = [
            ./hosts/installer.nix
            self.nixosModules.default
          ];
        };

        # Pi 5 build target. Use `nixos-raspberrypi.lib.nixosSystem`
        # (not `nixpkgs.lib.nixosSystem`) so the upstream's bootloader
        # / vendor-kernel / vendor-firmware / kernel-and-firmware
        # overlays are auto-applied. The opt-in `pkgs` overlay
        # (ffmpeg, kodi, etc.) is NOT applied — `nixosSystem` is the
        # node-friendly variant; `nixosSystemFull` would pull in the
        # media stack, which is wasted on a headless node.
        nixblitz-pi5 = nixos-raspberrypi.lib.nixosSystem {
          specialArgs = {
            inherit nixblitz nixos-raspberrypi;
            # Complete pinned source set — see `pinnedFlakeInputs` above.
            flakeInputs = pinnedFlakeInputs;
          };
          modules = [
            ./hosts/installed-pi5.nix
            self.nixosModules.default
          ];
        };

        # Pi 5 install target. Used by
        # `disko-install --flake .#nixblitz-pi5-installer` from inside
        # the live image (typically the upstream
        # `nvmd/nixos-raspberrypi#installerImages.rpi5` flashed to a
        # USB stick). Differs from `nixblitz-pi5` only in
        # `installer-pi5.nix`'s passwordless sudo override; same
        # bootloader / kernel / firmware / disko layout.
        nixblitz-pi5-installer = nixos-raspberrypi.lib.nixosSystem {
          specialArgs = {
            inherit nixblitz nixos-raspberrypi;
            # Complete pinned source set — see `pinnedFlakeInputs` above.
            flakeInputs = pinnedFlakeInputs;
          };
          modules = [
            ./hosts/installer-pi5.nix
            self.nixosModules.default
          ];
        };
      };

      # Hostname-keyed alias. NixOS rebuild defaults to
      # `${flake}#nixosConfigurations.${hostname}` when no `#attr`
      # is given; without this alias a Pi 5 system whose hostname
      # is the default `nixblitz` resolves to the x86 attribute
      # and fails with `boot.loader.grub.devices` unset. Aliasing
      # the hostname to the platform-correct build makes the bare
      # `sudo nixos-rebuild switch --flake .` (and the TUI's
      # update / apply paths that rely on the same default) DTRT
      # on every platform without the operator having to know the
      # `-pi5` attribute name.
      #
      # Default hostname `nixblitz` on x86: alias overwrites the
      # canonical `nixblitz` with the same value — no-op.
      # Default hostname `nixblitz` on Pi 5: alias overwrites the
      # canonical x86 `nixblitz` to point at the Pi 5 build —
      # exactly the footgun fix.
      # Custom hostname (e.g. `loki`) on either platform: alias
      # adds a new key pointing at the platform-correct build;
      # canonical names stay available for explicit `#nixblitz-*`.
      aliasTarget =
        if blitzPlatform == "pi5"
        then canonical.nixblitz-pi5
        else canonical.nixblitz;
    in
      canonical
      // {
        ${blitzHostname} = aliasTarget;
      };
  };
}
