# Generated by `just gen-completions` — do not edit by hand.
#
# Delegates `nixblitz <TAB>` completion to the binary's hidden
# `completion` subcommand. Protocol matches cli_completion's
# bash + zsh stubs (COMP_LINE + COMP_POINT env vars); see
# scripts/gen_completion_scripts.dart for the why.

def "nu-complete nixblitz" [context: string] {
  let line = $context
  let point = ($line | str length)

  let result = (
    with-env {
      COMP_CWORD: '0'
      COMP_LINE: $line
      COMP_POINT: ($point | into string)
    } {
      ^nixblitz completion --
    } | complete
  )

  if $result.exit_code != 0 {
    []
  } else {
    $result.stdout | lines | where { |l| ($l | str trim) != '' }
  }
}

export extern "nixblitz" [
  ...rest: string@"nu-complete nixblitz"
]
