// Generates shell completion scripts for the `nixblitz` binary into
// `tui/completions/nixblitz.{bash,zsh}`. Committed to the repo so the
// Nix package install hook can drop them at the standard NixOS paths
// (`$out/share/bash-completion/completions/nixblitz`,
// `$out/share/zsh/site-functions/_nixblitz`) without needing the
// binary to run install-completion-files at first launch.
//
// The scripts are generic shell stubs that call
// `nixblitz completion -- "${words[@]}"` at runtime; cli_completion's
// `HandleCompletionRequestCommand` does the actual command-tree
// completion server-side. That means these files change only when
// cli_completion's template changes (rare, on package upgrade), not
// when our command tree changes.
//
// Run: `just gen-completions`

import 'dart:io';

import 'package:cli_completion/installer.dart';
import 'package:path/path.dart' as p;

const _executableName = 'nixblitz';

void main(List<String> args) {
  // Resolve repo root relative to this script's location so the
  // generator works regardless of cwd (it's invoked from `just`).
  final repoRoot = _resolveRepoRoot();
  final outDir = p.join(repoRoot, 'tui', 'completions');
  Directory(outDir).createSync(recursive: true);

  // bash + zsh: cli_completion ships the templates.
  for (final shell in [SystemShell.bash, SystemShell.zsh]) {
    final config = ShellCompletionConfiguration.fromSystemShell(shell);
    final script = config.scriptTemplate(_executableName);
    final outPath = p.join(outDir, '$_executableName.${shell.name}');
    File(outPath).writeAsStringSync(script);
    stdout.writeln('wrote $outPath (${script.length} bytes)');
  }

  // nushell: hand-written stub since cli_completion only supports
  // bash + zsh upstream. Protocol is identical (COMP_LINE +
  // COMP_POINT env vars; the Dart parser ignores the positional
  // args after `--` and parses everything from COMP_LINE).
  final nuPath = p.join(outDir, '$_executableName.nu');
  File(nuPath).writeAsStringSync(_nushellTemplate(_executableName));
  stdout.writeln('wrote $nuPath');
}

/// Hand-written nushell completer template. Mirrors the protocol
/// of cli_completion's bash + zsh stubs: set `COMP_LINE` +
/// `COMP_POINT` + a placeholder `COMP_CWORD`, call
/// `<exe> completion --`, parse stdout as one suggestion per line.
///
/// `COMP_CWORD` is required (the Dart parser refuses to proceed if
/// it doesn't parse to an int) but its value isn't used downstream
/// — only `args` (split from COMP_LINE) and the argParser drive
/// the suggestion logic. Sending "0" keeps things simple.
String _nushellTemplate(String exe) {
  return '''
# Generated by `just gen-completions` — do not edit by hand.
#
# Delegates `$exe <TAB>` completion to the binary's hidden
# `completion` subcommand. Protocol matches cli_completion's
# bash + zsh stubs (COMP_LINE + COMP_POINT env vars); see
# scripts/gen_completion_scripts.dart for the why.

def "nu-complete $exe" [context: string] {
  let line = \$context
  let point = (\$line | str length)

  let result = (
    with-env {
      COMP_CWORD: '0'
      COMP_LINE: \$line
      COMP_POINT: (\$point | into string)
    } {
      ^$exe completion --
    } | complete
  )

  if \$result.exit_code != 0 {
    []
  } else {
    \$result.stdout | lines | where { |l| (\$l | str trim) != '' }
  }
}

export extern "$exe" [
  ...rest: string@"nu-complete $exe"
]
''';
}

/// Walk up from this script's path until a directory with `flake.nix`
/// + `tui/` is found. Falls back to `Directory.current` if the walk
/// hits the filesystem root.
String _resolveRepoRoot() {
  var dir = Directory(p.dirname(Platform.script.toFilePath()));
  while (true) {
    if (File(p.join(dir.path, 'flake.nix')).existsSync() &&
        Directory(p.join(dir.path, 'tui')).existsSync()) {
      return dir.path;
    }
    final parent = dir.parent;
    if (parent.path == dir.path) {
      // Hit /, give up — caller will see the path errors.
      return Directory.current.path;
    }
    dir = parent;
  }
}
