// GENERATED — do not edit. Run 'just gen-templates' to regenerate.
// Source: templates/

part of 'embedded_templates.dart';

const String _flake = r'''
{
  description = "NixBlitz node configuration";

  inputs = {
    nixpkgs.url = "github:nixOS/nixpkgs/nixos-25.11";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # nix-bitcoin used to be an input here, but it's pulled by the
    # bitcoind / lnd / cln plugins now via builtins.getFlake at a
    # coordinated rev. The operator's flake input list is shorter for it.
    nixblitz = {
      url = "git+https://forge.f44.fyi/f44/nixblitz_ng";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # Pi 5 isn't supported by upstream NixOS — vendor kernel + firmware
    # come from this third-party flake. Pinned to a tag so refreshes
    # are explicit; bump deliberately rather than tracking `main`.
    #
    # Deliberately NOT following nixpkgs (the only documented exception
    # to that rule besides `flake.nix`'s nixpkgs-unstable). nvmd's CI
    # publishes the vendor kernel + page-size-16k jemalloc to
    # `nixos-raspberrypi.cachix.org` built against THEIR pinned
    # nixpkgs; following ours diverges the derivation hash and forces
    # a Pi-local kernel rebuild — multi-hour aarch64 pain on every
    # nixpkgs bump. Closure cost (one extra nixpkgs snapshot, ~400MB)
    # is well below what we save in build time + thermal load.
    nixos-raspberrypi = {
      url = "github:nvmd/nixos-raspberrypi/v1.20260411.0";
    };
  };

  outputs = {
    self,
    nixpkgs,
    disko,
    nixblitz,
    nixos-raspberrypi,
  }: let
    inherit (nixpkgs) lib;

    excludedFiles = ["package.nix" "flake.nix"];

    findModules = dir: let
      entries = builtins.readDir dir;
      processEntry = name: type: let
        path = dir + "/${name}";
      in
        if type == "directory"
        then findModules path
        else if type == "regular" && lib.hasSuffix ".nix" name && !builtins.elem name excludedFiles
        then [path]
        else [];
    in
      lib.concatLists (lib.mapAttrsToList processEntry entries);

    # Read enough of the operator's config to know which platform
    # we're targeting AND to inject per-plugin config below. Used to
    # alias `nixosConfigurations.${hostname}` to the platform-correct
    # build (without it, a plain `nixos-rebuild switch --flake .`
    # defaults to `.#${hostname}` and the Pi 5 case grabs the x86
    # attribute, failing with `boot.loader.grub.devices` unset).
    blitzCfg =
      if builtins.pathExists ./config.json
      then builtins.fromJSON (builtins.readFile ./config.json)
      else {};
    blitzPlatform = blitzCfg.system.platform or "x86";
    blitzHostname = blitzCfg.system.hostname or "nixblitz";

    # User-installed plugins (see docs/decisions/plugins.md D14).
    # Activation is driven by ./plugins.list, regenerated by the TUI
    # on every install / remove / enable / disable. File format: one
    # plugin id per non-empty line. Each id resolves to a directory
    # under ./plugins/<id>/ that contains:
    #   - plugin.json: the manifest (declares `module` filename)
    #   - <module>:    the NixOS module file (default plugin.nix)
    #
    # Plugin ABI: the module is a TWO-STAGE function
    #   { pluginCfg ? {} }: { config, lib, pkgs, ... }: { … }
    # The outer stage receives the plugin's config from the main
    # config.json's `app_configs.<id>` block (single source of
    # truth — no per-plugin config.json). The inner is a standard
    # NixOS module function. We deliver pluginCfg via closure on the
    # outer stage, NOT as a named arg on the inner — because the
    # module system routes every named arg through `_module.args.<name>`,
    # which is global, so two plugins declaring `pluginCfg` as a
    # module arg would collide with `_module.args.pluginCfg' is
    # defined multiple times`. Two-stage isolates each plugin's cfg
    # inside its own closure.
    pluginModules = let
      pluginsListPath = ./plugins.list;
      pluginIds =
        if builtins.pathExists pluginsListPath
        then
          builtins.filter (s: s != "") (
            lib.splitString "\n" (builtins.readFile pluginsListPath)
          )
        else [];
      mkPluginModule = id: let
        pluginPath = ./plugins + "/${id}";
        manifest = builtins.fromJSON (
          builtins.readFile (pluginPath + "/plugin.json")
        );
        moduleFile = manifest.module or "plugin.nix";
        modulePath = pluginPath + "/${moduleFile}";
        # Plugin-specific config from the main config.json.
        # Defaults to {} — plugin manifests should provide sane
        # defaults via their config_schema, which the TUI seeds
        # into app_configs.<id> at install time.
        appConfigs = blitzCfg.app_configs or {};
        pluginCfg = appConfigs.${id} or {};
      in
        # `import modulePath` returns the outer function; calling
        # it with {pluginCfg = cfg} returns the inner module
        # function (no pluginCfg in that signature), which the
        # module system treats as a normal NixOS module.
        #
        # Plugins needing cross-app reads (e.g. blitz-api checking
        # whether lnd is enabled) get them via `config.nixblitz.
        # appConfigs.<id>.<key>` — declared as a NixOS option by
        # `templates/hosts/installed.nix`. No ABI change here; the
        # option-based path keeps the outer function signature
        # backwards-compatible with plugins that still use the
        # strict `{ pluginCfg ? {} }: …` shape.
        (import modulePath) {pluginCfg = pluginCfg;};
    in
      map mkPluginModule pluginIds;
  in {
    nixosModules.default = {
      imports =
        (findModules ./modules)
        ++ pluginModules
        ++ [
          disko.nixosModules.default
          # nix-bitcoin.nixosModules.default was here; the bitcoind / lnd /
          # cln plugins now import it themselves via builtins.getFlake at a
          # coordinated rev. blitz-api and blitz-web dropped from inputs too —
          # their plugins pull the upstream modules via `builtins.getFlake`.
          # See examples_redesign/nixblitz_official_plugins/.
        ];
    };

    # Build the four canonical configurations as a separate
    # attrset, then merge in the hostname-keyed alias below. The
    # split is purely so the alias can overwrite an existing key
    # (e.g. operator's hostname is the default `nixblitz` on Pi
    # 5 — alias overrides the x86 build under that name) without
    # tripping Nix's "attribute already defined" error from two
    # static assignments to the same key.
    nixosConfigurations = let
      canonical = {
        nixblitz = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          specialArgs = {inherit nixblitz;};
          modules = [
            ./hosts/installed.nix
            self.nixosModules.default
          ];
        };

        # Live-ISO config used by `disko-install --flake .#nixblitz-installer`.
        # Identical to nixosConfigurations.nixblitz except for passwordless
        # sudo. See docs/decisions/plugins.md (sudo posture).
        nixblitz-installer = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          specialArgs = {inherit nixblitz;};
          modules = [
            ./hosts/installer.nix
            self.nixosModules.default
          ];
        };

        # Pi 5 build target. Use `nixos-raspberrypi.lib.nixosSystem`
        # (not `nixpkgs.lib.nixosSystem`) so the upstream's bootloader
        # / vendor-kernel / vendor-firmware / kernel-and-firmware
        # overlays are auto-applied. The opt-in `pkgs` overlay
        # (ffmpeg, kodi, etc.) is NOT applied — `nixosSystem` is the
        # node-friendly variant; `nixosSystemFull` would pull in the
        # media stack, which is wasted on a headless node.
        nixblitz-pi5 = nixos-raspberrypi.lib.nixosSystem {
          specialArgs = {inherit nixblitz nixos-raspberrypi;};
          modules = [
            ./hosts/installed-pi5.nix
            self.nixosModules.default
          ];
        };

        # Pi 5 install target. Used by
        # `disko-install --flake .#nixblitz-pi5-installer` from inside
        # the live image (typically the upstream
        # `nvmd/nixos-raspberrypi#installerImages.rpi5` flashed to a
        # USB stick). Differs from `nixblitz-pi5` only in
        # `installer-pi5.nix`'s passwordless sudo override; same
        # bootloader / kernel / firmware / disko layout.
        nixblitz-pi5-installer = nixos-raspberrypi.lib.nixosSystem {
          specialArgs = {inherit nixblitz nixos-raspberrypi;};
          modules = [
            ./hosts/installer-pi5.nix
            self.nixosModules.default
          ];
        };
      };

      # Hostname-keyed alias. NixOS rebuild defaults to
      # `${flake}#nixosConfigurations.${hostname}` when no `#attr`
      # is given; without this alias a Pi 5 system whose hostname
      # is the default `nixblitz` resolves to the x86 attribute
      # and fails with `boot.loader.grub.devices` unset. Aliasing
      # the hostname to the platform-correct build makes the bare
      # `sudo nixos-rebuild switch --flake .` (and the TUI's
      # update / apply paths that rely on the same default) DTRT
      # on every platform without the operator having to know the
      # `-pi5` attribute name.
      #
      # Default hostname `nixblitz` on x86: alias overwrites the
      # canonical `nixblitz` with the same value — no-op.
      # Default hostname `nixblitz` on Pi 5: alias overwrites the
      # canonical x86 `nixblitz` to point at the Pi 5 build —
      # exactly the footgun fix.
      # Custom hostname (e.g. `loki`) on either platform: alias
      # adds a new key pointing at the platform-correct build;
      # canonical names stay available for explicit `#nixblitz-*`.
      aliasTarget =
        if blitzPlatform == "pi5"
        then canonical.nixblitz-pi5
        else canonical.nixblitz;
    in
      canonical
      // {
        ${blitzHostname} = aliasTarget;
      };
  };
}
''';

const String _hardwareVm = r'''
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "floppy" "sr_mod" "virtio_blk"];
      kernelModules = [];
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  disko.devices.disk.main = {
    device = lib.mkDefault "/dev/vda";
    type = "disk";
    content = {
      type = "gpt";
      partitions = {
        boot = {
          size = "1M";
          type = "EF02";
        };
        root = {
          size = "100%";
          content = {
            type = "filesystem";
            format = "ext4";
            mountpoint = "/";
          };
        };
      };
    };
  };

  boot.loader.grub = {
    enable = true;
    devices = ["/dev/vda"];
  };

  swapDevices = [];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  services.qemuGuest.enable = true;
}
''';

const String _hardwareX86 = r'''
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  disko.devices.disk.main = {
    device = lib.mkDefault "/dev/sda";
    type = "disk";
    content = {
      type = "gpt";
      partitions = {
        boot = {
          size = "1M";
          type = "EF02";
        };
        root = {
          size = "100%";
          content = {
            type = "filesystem";
            format = "ext4";
            mountpoint = "/";
          };
        };
      };
    };
  };

  boot.loader.grub.enable = true;
}
''';

const String _hostsDefault = r'''
{...}: {
  # Back-compat shim for any external flake referrers that still target
  # ./hosts/default.nix. The flake's nixosConfigurations now point
  # directly at installer.nix (live ISO) and installed.nix (post-install)
  # — see ../flake.nix.
  imports = [./installed.nix];
}
''';

const String _hostsInstalledPi5 = r'''
{
  config,
  lib,
  pkgs,
  nixos-raspberrypi,
  ...
}: {
  imports = [
    # Pi 5 vendor kernel + matched firmware. Comes from
    # `nvmd/nixos-raspberrypi`; the per-Pi attribute set is
    # documented at github.com/nvmd/nixos-raspberrypi. The
    # vendor kernel is configured for 16K pages at build time
    # (CONFIG_ARM64_16K_PAGES) — that's not something `.base` is
    # opting into, it's just what the hardware-friendly Pi 5
    # kernel ships with.
    nixos-raspberrypi.nixosModules.raspberry-pi-5.base
    # Optional-but-required-in-practice: rebuilds `pkgs.jemalloc`
    # with `--with-lg-page=14` (16K-aware). Without it, any C
    # binary on cache.nixos.org that links the system jemalloc
    # aborts with "Unsupported system page size" at startup
    # because cache.nixos.org's substitutes are built for 4K
    # alignment. See nvmd/nixos-raspberrypi#64.
    nixos-raspberrypi.nixosModules.raspberry-pi-5.page-size-16k
    # All the NixBlitz feature toggles, hostname, services, etc.
    # x86 and Pi 5 only differ in bootloader / kernel / firmware;
    # everything from `installed.nix` upward is platform-agnostic.
    ./installed.nix
  ];

  # Migrate off the legacy `kernelboot` default — the new
  # generational `kernel` bootloader supports rollback to a prior
  # generation via the boot menu, matching the experience x86
  # operators already have via systemd-boot.
  boot.loader.raspberry-pi.bootloader = "kernel";

  # Enable the Pi 5's onboard 4-pin fan header. Without this dtparam
  # the `cooling_fan` device tree node stays at its default
  # `status = "disabled"` and the kernel never enrolls the fan as
  # a thermal cooling device — `/sys/class/thermal/cooling_device*`
  # comes up empty, no PWM control reaches the fan, and the SoC
  # cooks under sustained load (kernel compile, etc). The vendor
  # `nixos-raspberrypi` flake doesn't turn this on by default.
  hardware.raspberry-pi.config.all.base-dt-params.cooling_fan = {
    enable = true;
    value = "on";
  };

  # 8 GB swapfile. The Pi 5 ships with 8 GB RAM, which is enough
  # for nix-bitcoin runtime but NOT enough to compile Rust workspaces
  # like `uv` from source — rustc + LLVM linker peak around 1-1.5 GB
  # per concurrent rustc, cargo schedules multiple within a single
  # build, and OOM-kills the whole `nixos-rebuild` (taking SSH and
  # the entire system with it) midway through the closure. A swapfile
  # absorbs the spike at the cost of some I/O. Future Pi-local
  # rebuilds that miss the cachix substituters (e.g. when the
  # nixpkgs pin moves past what nvmd's CI has built) need this to
  # finish at all.
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 8 * 1024;
    }
  ];
}
''';

const String _hostsInstalled = r'''
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = builtins.fromJSON (builtins.readFile ../config.json);
  sys = cfg.system;
  # Bootstrap gate: during initial install, `initialized` is false and all
  # services are forced off so disko-install builds a minimal system that
  # fits in the live ISO's tmpfs. After first-boot setup, `initialized`
  # flips to true and the real service configuration is built on the
  # installed system's disk (plenty of space).
  initialized = cfg.initialized or false;

  # Generic helpers for the v18 app_configs shape.
  # `apps` is the map of app-name → config-map from config.json.
  apps = cfg.app_configs or {};

  # Read a single option from apps.<name>.<key>, falling back to `default`
  # when the app entry or the key is absent.
  appOpt = name: key: default: let
    m = apps.${name} or {};
  in
    m.${key} or default;

  # An app is active only when the system has been initialized AND the app's
  # own `enabled` flag is true.
  appEnabled = name: initialized && (appOpt name "enabled" false);
in {
  imports = [
    ../hardware-configuration.nix
  ];

  # Feed the appConfigs option declared in
  # modules/system/nixblitz-options.nix (auto-imported via
  # findModules). Plugins read this as
  # `config.nixblitz.appConfigs.<id>.<key>` for cross-app state
  # (e.g. blitz-api gating on lnd.enabled).
  nixblitz.appConfigs = apps;

  networking.hostName = sys.hostname;
  time.timeZone = sys.timezone;

  features.system.base.enable = true;
  # Operator's choice of login shell. Older configs (pre-v16) don't
  # have the field — fall back to bash, the new default.
  features.system.base.shell = sys.shell or "bash";

  # Two background timers (daily light + weekly heavy) populate
  # ~/.local/state/nixblitz/update-status.json so the dashboard can
  # surface "X updates available" without the user kicking off a
  # rebuild. See templates/modules/system/update-check.nix.
  features.system.updateCheck.enable = initialized;

  # Disk layout — enable the appropriate disko config for the platform.
  # `disk_device` carries the operator's choice from the install wizard
  # forward to subsequent rebuilds; without it, post-install rebuilds
  # default the disko `device` to `/dev/vda` and grub-install fails on
  # bare metal where the disk is `/dev/sda`. Empty string falls back to
  # the disko module's per-platform default for VMs that pre-date the
  # field.
  features.system.disko-x86.enable = sys.platform == "vm" || sys.platform == "x86";
  features.system.disko-x86.device =
    if (sys.disk_device or "") != ""
    then sys.disk_device
    else "/dev/vda";
  features.system.disko-pi5.enable = sys.platform == "pi5";

  # Test-LND: secondary regtest-only LND instance for opening channels
  # against the primary node and dry-running payments via `lncli-test`.
  # Auto-enabled whenever bitcoind is on regtest; off on any real network.
  features.system.testLnd.enable =
    (appEnabled "bitcoind")
    && (appOpt "bitcoind" "network" "mainnet") == "regtest"
    && (appEnabled "lnd");

  users.users.admin = {
    isNormalUser = true;
    extraGroups = ["wheel"];
    initialPassword = "nixblitz";
  };

  # NixOS default: wheelNeedsPassword = true. The TUI authenticates
  # sudo via the SudoSession service (sudo -S -v + ~10 min keepalive),
  # so all privileged flows still work non-interactively after one
  # password prompt per session of activity.
  services.openssh.enable = true;

  system.stateVersion = "25.11";
}
''';

const String _hostsInstallerPi5 = r'''
{
  config,
  lib,
  pkgs,
  ...
}: {
  # Live-image host config for Pi 5, used by
  # `disko-install --flake .#nixblitz-pi5-installer`. Mirrors
  # `installer.nix`: identical to the installed system except for
  # passwordless sudo so the install wizard's privileged steps
  # (disko-install, nixos-generate-config, mount, cp, …) run
  # non-interactively. The booted live image is ephemeral; the
  # installed system inherits NixOS's `wheelNeedsPassword=true`
  # default.
  imports = [./installed-pi5.nix];

  security.sudo.wheelNeedsPassword = false;
}
''';

const String _hostsInstaller = r'''
{
  config,
  lib,
  pkgs,
  ...
}: {
  # Live ISO host config, used by `disko-install --flake .#nixblitz-installer`.
  # Differs from the installed system in exactly one place: passwordless sudo,
  # so the TUI's install-time wizard (disko-install, nixos-generate-config,
  # mount, cp, chown, …) can run non-interactively. The live ISO is
  # ephemeral and has no persistent attacker, so this is the right default
  # here. The installed system uses NixOS's wheelNeedsPassword=true default.
  imports = [./installed.nix];

  security.sudo.wheelNeedsPassword = false;
}
''';

const String _modulesSystemBase = r'''
{
  config,
  lib,
  pkgs,
  nixblitz,
  ...
}: let
  cfg = config.features.system.base;
in {
  options.features.system.base = {
    enable = lib.mkEnableOption "base NixBlitz system configuration";

    # The TUI surfaces this as a select in Configure → system. Both
    # candidates ship in environment.systemPackages below so flipping
    # the choice doesn't trigger a fresh closure download.
    shell = lib.mkOption {
      type = lib.types.enum ["bash" "nushell"];
      default = "bash";
      description = "Default login shell for the admin user.";
    };
  };

  config = lib.mkIf cfg.enable {
    nix.settings = {
      experimental-features = ["nix-command" "flakes"];
      trusted-users = ["root" "admin"];
    };

    environment.systemPackages = with pkgs; [
      git
      jujutsu
      htop
      btop
      tree
      jq
      bat
      fd
      ripgrep
      neovim
      yazi
      systemctl-tui
      # Used by the TUI's Update view to render a per-package
      # version diff (`[U.] bitcoind 27.1, 27.2`) between the
      # running system and the dry-built next generation. Tiny
      # closure; also useful at the shell.
      nvd
      # Both shells are kept available regardless of the
      # `defaultUserShell` choice — operators flipping the option
      # via Configure shouldn't have to wait on a new closure
      # fetch, and a `nu` / `bash` invocation from a script keeps
      # working.
      bashInteractive
      nushell
      nixblitz.packages.${pkgs.system}.nixblitz-unwrapped
    ];

    users.defaultUserShell =
      if cfg.shell == "nushell"
      then pkgs.nushell
      else pkgs.bashInteractive;

    # Auto-launch the NixBlitz TUI on the first interactive login of
    # a session. Two snippets — one for each supported shell — both
    # installed unconditionally so a Configure → system → shell flip
    # works on the next login without re-activating the system. Only
    # the active shell sources its file.
    #
    # `NIXBLITZ_AUTOLAUNCHED` prevents recursion: nixblitz spawns
    # subshells (e.g. password change runs `chpasswd`) that would
    # otherwise re-trigger the auto-launch from inside themselves.
    # The bash variant additionally guards on `-t 0` / `-t 1` so
    # non-TTY contexts (`ssh admin@host nixos-rebuild switch`, cron,
    # build scripts) don't drop into the TUI. nushell's login.nu
    # only fires on login shells so the SSH-with-command path skips
    # naturally there.
    environment.etc."nixblitz/auto-launch.sh".text = ''
      if [ -z "''${NIXBLITZ_AUTOLAUNCHED:-}" ] && [ -t 0 ] && [ -t 1 ] \
          && command -v nixblitz >/dev/null 2>&1; then
        export NIXBLITZ_AUTOLAUNCHED=1
        nixblitz
      fi
    '';

    environment.etc."nixblitz/auto-launch.nu".text = ''
      if ($env.NIXBLITZ_AUTOLAUNCHED? | default "") == "" {
        $env.NIXBLITZ_AUTOLAUNCHED = "1"
        if (which nixblitz | length) > 0 {
          nixblitz
        }
      }
    '';

    programs.bash.interactiveShellInit = ''
      [ -r /etc/nixblitz/auto-launch.sh ] && . /etc/nixblitz/auto-launch.sh
    '';

    # NixOS has no `programs.nushell` module, so wire nushell up by
    # symlinking the system snippet into the admin user's config dir.
    # `login.nu` is nushell's analogue to `/etc/profile` — runs once
    # at login, not on every interactive `nu` subshell. The `d` rules
    # ensure the parent dirs exist; `L+` overwrites any existing
    # symlink so re-activations stay idempotent.
    systemd.tmpfiles.rules = [
      "d /home/admin/.config 0755 admin users -"
      "d /home/admin/.config/nushell 0755 admin users -"
      "L+ /home/admin/.config/nushell/login.nu - admin users - /etc/nixblitz/auto-launch.nu"
    ];
  };
}
''';

const String _modulesSystemDiskoPi5 = r'''
{
  config,
  lib,
  ...
}: let
  cfg = config.features.system.disko-pi5;
in {
  options.features.system.disko-pi5.enable =
    lib.mkEnableOption "Pi 5 disk layout (GPT, FAT firmware + ext4 root)";

  config = lib.mkIf cfg.enable {
    # Pi 5 boot path needs a FAT partition for vendor firmware,
    # device-tree blobs, overlays, and (with the `kernel`
    # bootloader from nvmd/nixos-raspberrypi) per-generation
    # kernel images. Mount point matches the upstream module's
    # default `boot.loader.raspberry-pi.firmwarePath` so we don't
    # have to wire that through here.
    #
    # Default device targets NVMe (the supported configuration
    # via the official M.2 HAT) but `disko-install --disk main
    # <path>` overrides this at install time, so the user can
    # pick SD / USB / NVMe at the wizard step regardless.
    disko.devices.disk.main = {
      device = lib.mkDefault "/dev/nvme0n1";
      type = "disk";
      content = {
        type = "gpt";
        partitions = {
          firmware = {
            # 1 GB headroom matches the upstream installer
            # image's `sdImage.firmwareSize = 1024` so multiple
            # NixOS generations + their kernels fit alongside the
            # vendor firmware blobs.
            size = "1024M";
            type = "EF00";
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot/firmware";
              # 0077 keeps the firmware partition root-owned —
              # nothing should be reading kernel images from
              # here at runtime.
              mountOptions = ["umask=0077"];
            };
          };
          root = {
            size = "100%";
            content = {
              type = "filesystem";
              format = "ext4";
              mountpoint = "/";
            };
          };
        };
      };
    };
  };
}
''';

const String _modulesSystemDiskoX86 = r'''
{
  config,
  lib,
  ...
}: let
  cfg = config.features.system.disko-x86;
in {
  options.features.system.disko-x86 = {
    enable =
      lib.mkEnableOption
      "x86 disk layout (GPT, BIOS-boot + ESP + ext4 root)";

    device = lib.mkOption {
      type = lib.types.str;
      default = "/dev/vda";
      description = ''
        Block device to install onto. Defaults to `/dev/vda`
        (the qemu virtio default, fine for VMs); overridden to
        the operator's actual install target on bare metal.
        Without an override, post-install rebuilds on bare-metal
        x86 try to install GRUB onto a non-existent /dev/vda.
        Set by `installed.nix` from `system.disk_device` in
        `config.json`, which the install wizard records before
        running disko-install.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Hybrid GPT layout — boots on both BIOS (qemu/Proxmox/older
    # hardware) and UEFI (essentially every modern x86 board)
    # without operator intervention. Three partitions:
    #
    # 1. `bios` (1 MB, type EF02): GRUB's BIOS-boot partition.
    #    No filesystem; GRUB embeds its core image directly into
    #    the partition bytes.
    # 2. `esp` (512 MB, type EF00, FAT32): the EFI System
    #    Partition. Mounted at /boot. Holds the GRUB EFI binary
    #    + the kernel / initrd images.
    # 3. `root` (rest, ext4): the system + /nix/store + /home.
    #
    # Without the ESP, a UEFI machine can't find an EFI binary
    # and hangs at firmware setup ("no boot device") — which is
    # exactly the regression that hit the operator's first
    # bare-metal install. Adding the ESP costs 512 MB and makes
    # the same image portable across firmware modes.
    disko.devices.disk.main = {
      device = cfg.device;
      type = "disk";
      content = {
        type = "gpt";
        partitions = {
          bios = {
            size = "1M";
            type = "EF02";
            # Must come first on the disk for GRUB's BIOS embed
            # to find it.
            priority = 1;
          };
          esp = {
            size = "512M";
            type = "EF00";
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
              # Restrict the firmware partition to root — nothing
              # at runtime should be reading kernels from there.
              mountOptions = ["umask=0077"];
            };
          };
          root = {
            size = "100%";
            content = {
              type = "filesystem";
              format = "ext4";
              mountpoint = "/";
            };
          };
        };
      };
    };

    # GRUB in dual-mode: BIOS install lands on the EF02
    # partition (disko sets boot.loader.grub.devices for us),
    # EFI install lands at /EFI/BOOT/BOOTX64.EFI on the ESP.
    # `efiInstallAsRemovable = true` uses the standard fallback
    # path, so the firmware finds the binary without needing an
    # NVRAM entry — robust for VMs (no persistent NVRAM) and
    # reinstalls onto different disks.
    boot.loader.grub = {
      enable = true;
      efiSupport = true;
      efiInstallAsRemovable = true;
    };
  };
}
''';

const String _modulesSystemNixblitzOptions = r'''
{lib, ...}: {
  # Read-only view of `config.json`'s `app_configs.*` block, exposed
  # at the NixOS-config level so plugins can do cross-app reads
  # without depending on a plugin ABI extension.
  #
  # E.g. blitz-api checks `config.nixblitz.appConfigs.lnd.enabled or
  # false` to decide whether to wire LND's admin macaroon. Replaces
  # the `config.features.apps.<id>.{enable,network}` accessor that
  # came out with the bitcoind/lnd/cln plugin extraction — that
  # wiring assumed every core app had a NixOS-options frontend, but
  # extracted plugins no longer declare those options.
  #
  # Type is deliberately loose (`attrsOf attrs`) — the shape of each
  # app's block is whatever its plugin's `config_schema` declares,
  # and we don't want to repeat that schema here. Plugins read
  # individual keys with `or default` fallbacks.
  #
  # The option is FED from `templates/hosts/installed.nix`'s `apps =
  # cfg.app_configs or {}` let-binding (single source of truth — the
  # same map the helpers `appOpt` / `appEnabled` consume).
  options.nixblitz.appConfigs = lib.mkOption {
    type = lib.types.attrsOf (lib.types.attrsOf lib.types.unspecified);
    default = {};
    description = ''
      The `app_configs.*` block from `~/nixblitz/config.json`,
      exposed for cross-plugin reads. Plugins access individual
      keys via `config.nixblitz.appConfigs.<id>.<key> or default`.
    '';
  };
}
''';

const String _modulesSystemTestLnd = r'''
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.features.system.testLnd;

  user = "lnd-test";
  group = "lnd-test";
  dataDir = "/var/lib/lnd-test";
  pwFile = "${dataDir}/.wallet-password";
  seedFile = "${dataDir}/.seed-mnemonic";
  # Sentinel we write only after lndinit init-wallet succeeds. Using a
  # marker (instead of "wallet.db exists") means a partial half-init
  # from an earlier failing config doesn't fool us into skipping the
  # real init on the next boot.
  initMarker = "${dataDir}/.wallet-initialized";
  # LND's own layout — chain/ sits directly under dataDir, NOT under a
  # data/ subdir. Matches nix-bitcoin's services.lnd.networkDir.
  networkDir = "${dataDir}/chain/bitcoin/regtest";

  # Reference the primary bitcoind the nix-bitcoin module defines.
  # We talk to it via the group-readable regtest cookie file — no need
  # to thread nix-bitcoin's secrets through for a local test node.
  bitcoind = config.services.bitcoind;
  cookiePath = "${bitcoind.dataDir}/regtest/.cookie";

  # nix-bitcoin ships the `lndinit` helper for headless wallet creation.
  # Grab it from their package set; we already import nix-bitcoin's
  # default NixOS module elsewhere in the system.
  lndinit = "${config.nix-bitcoin.pkgs.lndinit}/bin/lndinit";

  # ZMQ publisher URLs come from nix-bitcoin in tcp://0.0.0.0:PORT form
  # (or [::]); LND won't resolve those to loopback by itself, so swap
  # them to explicit localhost.
  zmqFix = builtins.replaceStrings ["0.0.0.0" "[::]"] ["127.0.0.1" "[::1]"];

  # Alt ports so we don't collide with the primary LND.
  p2pPort = 9736;
  rpcPort = 10010;
  restPort = 8081;

  configFile = pkgs.writeText "lnd-test.conf" ''
    datadir=${dataDir}
    tlscertpath=${dataDir}/tls.cert
    tlskeypath=${dataDir}/tls.key

    # journald already timestamps + tags; no need to log to file.
    logging.file.disable=1
    logging.console.no-timestamps=1

    listen=127.0.0.1:${toString p2pPort}
    rpclisten=127.0.0.1:${toString rpcPort}
    restlisten=127.0.0.1:${toString restPort}

    bitcoin.regtest=1
    bitcoin.node=bitcoind

    bitcoind.rpchost=127.0.0.1:${toString bitcoind.rpc.port}
    bitcoind.rpccookie=${cookiePath}
    bitcoind.zmqpubrawblock=${zmqFix bitcoind.zmqpubrawblock}
    bitcoind.zmqpubrawtx=${zmqFix bitcoind.zmqpubrawtx}

    # The wallet is created headlessly in preStart via lndinit; LND then
    # auto-unlocks on every subsequent boot from the same password file.
    wallet-unlock-password-file=${pwFile}
  '';

  # Admin-friendly wrapper: no arguments needed to hit the right
  # rpcserver/cert/macaroon combo.
  lncliTest = pkgs.writeShellScriptBin "lncli-test" ''
    exec ${pkgs.lnd}/bin/lncli \
      -n regtest \
      --rpcserver=127.0.0.1:${toString rpcPort} \
      --tlscertpath=${dataDir}/tls.cert \
      --macaroonpath=${networkDir}/admin.macaroon \
      "$@"
  '';
in {
  options.features.system.testLnd = {
    enable =
      lib.mkEnableOption
      "secondary LND instance for regtest testing — NOT for production";
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = bitcoind.regtest;
        message =
          "features.system.testLnd requires bitcoind running on regtest. "
          + "Set app_configs.bitcoind.network = \"regtest\" in config.json first.";
      }
    ];

    users.users.${user} = {
      isSystemUser = true;
      group = group;
      home = dataDir;
      description = "lnd-test (regtest-only secondary LND)";
      # Need the bitcoin group to read bitcoind's regtest cookie file.
      extraGroups = [bitcoind.group];
    };
    users.groups.${group} = {};

    # Admin gets group-read access to the macaroon so `lncli-test`
    # works without sudo.
    users.users.admin.extraGroups = [group];

    systemd.services.lnd-test = {
      wantedBy = ["multi-user.target"];
      requires = ["bitcoind.service"];
      after = ["bitcoind.service"];
      description = "lnd-test (regtest-only secondary LND)";
      preStart = ''
        set -eu
        # Trace every command so the journal shows exactly what ran.
        set -x

        # Debug snapshot of state on entry.
        ${pkgs.coreutils}/bin/ls -la ${dataDir} \
          || echo "(dataDir doesn't exist yet)"

        # One-time wallet password seed; persists across reboots and
        # rebuilds so the wallet stays unlockable.
        if [ ! -s ${pwFile} ]; then
          ${pkgs.coreutils}/bin/tr -dc '[:alnum:]' < /dev/urandom \
            | ${pkgs.coreutils}/bin/head -c 64 > ${pwFile}
          chmod 600 ${pwFile}
        fi

        # Headless wallet init on first boot. LND's `wallet-unlock-password-file`
        # only *unlocks* an existing wallet — creation has to happen out
        # of band via lndinit. Use a marker file we only touch after a
        # successful init so stale wallet fragments from a previous
        # broken attempt force a clean re-init.
        if [ ! -f ${initMarker} ]; then
          echo "lnd-test: wallet not initialized, running lndinit"

          # Nuke any leftover chain state so lndinit starts from
          # scratch. Also clear the bogus `data/` subdir left behind
          # by earlier broken runs of this module.
          ${pkgs.coreutils}/bin/rm -rf \
            ${dataDir}/chain \
            ${dataDir}/data \
            ${dataDir}/graph \
            ${dataDir}/.lnd

          if [ ! -s ${seedFile} ]; then
            (umask 0077; ${lndinit} gen-seed > ${seedFile})
          fi
          ${pkgs.coreutils}/bin/mkdir -p ${networkDir}

          ${lndinit} -v init-wallet \
            --file.seed=${seedFile} \
            --file.wallet-password=${pwFile} \
            --init-file.output-wallet-dir=${networkDir}

          ${pkgs.coreutils}/bin/ls -la ${networkDir}
          ${pkgs.coreutils}/bin/touch ${initMarker}
          echo "lnd-test: wallet init complete, marker written"
        else
          echo "lnd-test: wallet already initialized (marker present)"
        fi
      '';
      serviceConfig = {
        Type = "notify";
        ExecStart = "${pkgs.lnd}/bin/lnd --configfile=${configFile}";
        # The ReadWritePaths on StateDirectory gives us the dataDir.
        StateDirectory = "lnd-test";
        StateDirectoryMode = "0750";
        User = user;
        Group = group;
        TimeoutStartSec = "15min";
        Restart = "on-failure";
        RestartSec = "10s";
        # LND generates tls.cert very early (before wallet unlock) and
        # admin.macaroon shortly after. Chgrp both to the lnd-test group
        # so the admin user (member of that group) can use lncli-test.
        # tls.cert is chmod'd as soon as it appears; macaroon chmod
        # waits for the wallet to finish unlocking.
        ExecStartPost = pkgs.writeShellScript "lnd-test-perms" ''
          cert=${dataDir}/tls.cert
          mac=${networkDir}/admin.macaroon

          # tls.cert: relax perms immediately once LND has written it.
          for _ in $(${pkgs.coreutils}/bin/seq 1 30); do
            if [ -f "$cert" ]; then
              ${pkgs.coreutils}/bin/chgrp ${group} "$cert" || true
              ${pkgs.coreutils}/bin/chmod 640 "$cert" || true
              break
            fi
            ${pkgs.coreutils}/bin/sleep 0.5
          done

          # admin.macaroon: appears after wallet unlock. Also unlock the
          # intermediate dirs so group traversal works.
          for _ in $(${pkgs.coreutils}/bin/seq 1 60); do
            if [ -f "$mac" ]; then
              ${pkgs.coreutils}/bin/chgrp ${group} "$mac" || true
              ${pkgs.coreutils}/bin/chmod 640 "$mac" || true
              ${pkgs.coreutils}/bin/chmod g+rx \
                ${dataDir}/chain \
                ${dataDir}/chain/bitcoin \
                ${networkDir} || true
              exit 0
            fi
            ${pkgs.coreutils}/bin/sleep 0.5
          done
          # Best-effort; don't fail startup if macaroon isn't there yet.
          exit 0
        '';
      };
    };

    environment.systemPackages = [lncliTest];
  };
}
''';

const String _modulesSystemUpdateCheck = r'''
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.features.system.updateCheck;
  # Where the checker writes its result. The TUI dashboard banner
  # reads from this. Path mirrored in
  # `common/lib/src/models/update_status.dart` (`updateStatusPath`).
  stateDir = "/var/lib/nixblitz-tui";
in {
  options.features.system.updateCheck = {
    enable = lib.mkEnableOption ''
      Periodic upstream-update checks for the dashboard banner.
      Two timers: a daily lightweight one (GitHub/Forgejo HEAD via
      API; ~kB transfer) and a weekly heavy one (full
      `nix flake update` + `nvd diff` in a tmpdir; ~125 MB).
    '';
  };

  config = lib.mkIf cfg.enable {
    # Owned by admin so the timer-driven `nixblitz check ...`
    # invocations (run as User=admin) can write their results here.
    systemd.tmpfiles.rules = [
      "d ${stateDir} 0755 admin users -"
    ];

    systemd.services.nixblitz-check-light = {
      description = "NixBlitz: query upstream HEAD for each flake input";
      after = ["network-online.target"];
      wants = ["network-online.target"];
      serviceConfig = {
        Type = "oneshot";
        User = "admin";
        # Resolve nixblitz via the system PATH so the wrapper
        # picks up disko + git like an interactive shell would.
        ExecStart = "${pkgs.runtimeShell} -lc 'nixblitz check light'";
      };
    };

    systemd.timers.nixblitz-check-light = {
      description = "NixBlitz lightweight update check (daily)";
      wantedBy = ["timers.target"];
      timerConfig = {
        OnCalendar = "daily";
        Persistent = true;
        # Avoid every NixBlitz on the planet hitting GitHub at
        # exactly midnight — spread the load up to an hour.
        RandomizedDelaySec = "1h";
      };
    };

    systemd.services.nixblitz-check-heavy = {
      description = "NixBlitz: weekly nix flake update + nvd diff in tmpdir";
      after = ["network-online.target"];
      wants = ["network-online.target"];
      serviceConfig = {
        Type = "oneshot";
        User = "admin";
        ExecStart = "${pkgs.runtimeShell} -lc 'nixblitz check heavy'";
        # Heavy check pulls tarballs + evaluates a NixOS system —
        # 5-10 min on a Pi, ~1-2 min on x86. Cap so a stuck run
        # doesn't keep a timer locked indefinitely.
        TimeoutStartSec = "30min";
      };
    };

    systemd.timers.nixblitz-check-heavy = {
      description = "NixBlitz heavy update check (weekly)";
      wantedBy = ["timers.target"];
      timerConfig = {
        OnCalendar = "weekly";
        Persistent = true;
        # Spread up to 6h so simultaneous evaluations don't
        # thrash binary caches.
        RandomizedDelaySec = "6h";
      };
    };
  };
}
''';

Map<String, String> _getAllTemplates() {
  return {
    'flake.nix': _flake,
    'hardware/vm.nix': _hardwareVm,
    'hardware/x86.nix': _hardwareX86,
    'hosts/default.nix': _hostsDefault,
    'hosts/installed-pi5.nix': _hostsInstalledPi5,
    'hosts/installed.nix': _hostsInstalled,
    'hosts/installer-pi5.nix': _hostsInstallerPi5,
    'hosts/installer.nix': _hostsInstaller,
    'modules/system/base.nix': _modulesSystemBase,
    'modules/system/disko-pi5.nix': _modulesSystemDiskoPi5,
    'modules/system/disko-x86.nix': _modulesSystemDiskoX86,
    'modules/system/nixblitz-options.nix': _modulesSystemNixblitzOptions,
    'modules/system/test-lnd.nix': _modulesSystemTestLnd,
    'modules/system/update-check.nix': _modulesSystemUpdateCheck,
  };
}
